const db=supabase.createClient(SITE_CONFIG.SUPABASE_URL,SITE_CONFIG.SUPABASE_ANON_KEY);const allowed=(SITE_CONFIG.ADMIN_EMAILS||[]).map(x=>x.toLowerCase());const $=id=>document.getElementById(id);let state={events:[],invitations:[],assignments:[],rsvps:[],responses:[],selected:'all',editing:null};const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const show=id=>$(id).classList.remove('hidden'),hide=id=>$(id).classList.add('hidden');
async function login(){authMessage.textContent='Opening Google sign-in...';const{error}=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${location.origin}/admin.html`}});if(error)authMessage.textContent=error.message}async function logout(){await db.auth.signOut();location.replace('/admin.html')}async function route(session){['loginView','deniedView','appView','signOut'].forEach(hide);if(!session){show('loginView');return}const email=(session.user.email||'').toLowerCase();if(!allowed.includes(email)){deniedEmail.textContent=`Signed in as ${session.user.email}`;show('deniedView');return}signedInAs.textContent=session.user.email;show('appView');show('signOut');await loadAll()}
async function loadAll(){managerMessage.textContent='Loading live data...';const[e,i,a,r,x]=await Promise.all([db.from('events').select('*').order('starts_at'),db.from('invitations').select('*').order('primary_name'),db.from('invitation_events').select('*'),db.from('rsvps').select('*'),db.from('rsvp_events').select('*')]);const error=e.error||i.error||a.error||r.error||x.error;if(error){managerMessage.textContent=error.message;return}state.events=e.data||[];state.invitations=i.data||[];state.assignments=a.data||[];state.rsvps=r.data||[];state.responses=x.data||[];managerMessage.textContent='';renderEventCards();renderFamilies();renderEventOptions()}
function rsvpForInvitation(id){return state.rsvps.find(r=>r.invitation_id===id)}function responseFor(invitationId,eventId){const r=rsvpForInvitation(invitationId);return r?state.responses.find(x=>x.rsvp_id===r.id&&x.event_id===eventId):null}function invitationsForEvent(eventId){const ids=new Set(state.assignments.filter(a=>a.event_id===eventId).map(a=>a.invitation_id));return state.invitations.filter(i=>ids.has(i.id))}function statusFor(inv,eventId){if(eventId==='all'){const assigned=state.assignments.filter(a=>a.invitation_id===inv.id);if(!assigned.length)return'pending';const statuses=assigned.map(a=>responseFor(inv.id,a.event_id)?.status||'pending');return statuses.every(x=>x==='no')?'no':statuses.some(x=>x==='yes')?'yes':'pending'}return responseFor(inv.id,eventId)?.status||'pending'}function attendanceFor(inv,eventId){const r=rsvpForInvitation(inv.id);if(!r||statusFor(inv,eventId)!=='yes')return 0;return Number(r.adults||0)+Number(r.children||0)}
function renderEventCards(){const all={name:'All families',id:'all'};const cards=[all,...state.events];eventCards.innerHTML=cards.map((e,index)=>{const list=e.id==='all'?state.invitations:invitationsForEvent(e.id);const yes=list.filter(i=>statusFor(i,e.id)==='yes').length,pending=list.filter(i=>statusFor(i,e.id)==='pending').length,people=list.reduce((s,i)=>s+attendanceFor(i,e.id),0);const accent=['#d29c80','#9b4629','#d1a457','#7d8a71'][index%4];return`<button class="event-summary ${state.selected===e.id?'active':''}" data-event="${e.id}" style="--event-accent:${accent}"><small>${e.id==='all'?'MASTER LIST':new Date(e.starts_at).toLocaleDateString('en-CA',{month:'short',day:'numeric'})}</small><h3>${esc(e.name)}</h3><div class="event-count">${list.length}</div><div class="event-meta"><span>${yes} confirmed</span><span>${pending} pending</span><span>${people} people</span></div></button>`}).join('');document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.event;statusFilter.value='all';renderEventCards();renderFamilies()})}
function renderFamilies(){const event=state.events.find(e=>e.id===state.selected);managerTitle.textContent=event?event.name:'All families';managerSubtitle.textContent=event?`Families invited to ${event.name}.`:'View every family and their invitation assignments.';let list=event?invitationsForEvent(event.id):[...state.invitations];const q=familySearch.value.trim().toLowerCase(),sf=statusFilter.value;list=list.filter(i=>!q||[i.primary_name,i.token,i.phone,i.email,i.category].join(' ').toLowerCase().includes(q)).filter(i=>sf==='all'||statusFor(i,state.selected)===sf);familiesGrid.innerHTML=list.length?list.map(i=>{const status=statusFor(i,state.selected),r=rsvpForInvitation(i.id),count=attendanceFor(i,state.selected),assigned=state.assignments.filter(a=>a.invitation_id===i.id).map(a=>state.events.find(e=>e.id===a.event_id)?.name).filter(Boolean);return`<article class="family-row"><div class="family-main"><b>${esc(i.primary_name)}</b><small>${assigned.map(esc).join(' · ')||'No events assigned'}</small></div><div><span class="code-pill">${esc(i.token)}</span></div><div><span class="status-pill status-${status}">${status==='yes'?'Confirmed':status==='no'?'Declined':'Pending'}</span></div><div class="attendance"><strong>${count||'—'}</strong><small>${r?`${r.adults||0} adults · ${r.children||0} children`:'No RSVP'}</small></div><div class="row-actions"><button class="icon-button" data-copy="${esc(i.token)}">Copy link</button><button class="icon-button" data-wa="${i.id}">WhatsApp</button><button class="icon-button" data-edit="${i.id}">Edit</button></div></article>`}).join(''):'<div class="empty-state">No families match this view.</div>';document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copyLink(b.dataset.copy));document.querySelectorAll('[data-wa]').forEach(b=>b.onclick=()=>openWhatsApp(b.dataset.wa));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openFamily(b.dataset.edit))}
function renderEventOptions(){eventOptions.innerHTML=state.events.map(e=>`<label class="event-choice"><input type="checkbox" name="familyEvent" value="${e.id}"><span>${esc(e.name)}</span></label>`).join('')}
function makeCode(name){return name.toUpperCase().replace(/FAMILY/g,'').replace(/[^A-Z0-9]/g,'').slice(0,30)}function updatePreview(){const code=familyCode.value.trim().toUpperCase()||'CODE';linkPreview.textContent=`${location.origin}/invite.html?token=${code}`}function openFamily(id=null){state.editing=id;familyForm.reset();formMessage.textContent='';deleteFamily.classList.toggle('hidden',!id);dialogTitle.textContent=id?'Edit family':'Add family';if(id){const i=state.invitations.find(x=>x.id===id);familyId.value=i.id;familyName.value=i.primary_name;familyCode.value=i.token;familyCategory.value=i.category||'Friends';familyPhone.value=i.phone||'';familyEmail.value=i.email||'';const ids=new Set(state.assignments.filter(a=>a.invitation_id===id).map(a=>a.event_id));document.querySelectorAll('[name=familyEvent]').forEach(x=>x.checked=ids.has(x.value))}else{familyId.value='';familyCategory.value='Friends';document.querySelectorAll('[name=familyEvent]').forEach(x=>x.checked=state.selected!=='all'&&x.value===state.selected)}updatePreview();familyDialog.showModal()}
async function saveFamilyRecord(e){e.preventDefault();const eventIds=[...document.querySelectorAll('[name=familyEvent]:checked')].map(x=>x.value);if(!eventIds.length){formMessage.textContent='Select at least one event.';return}const code=familyCode.value.trim().toUpperCase();if(!/^[A-Z0-9-]{2,30}$/.test(code)){formMessage.textContent='Code must use 2–30 letters, numbers or hyphens.';return}saveFamily.disabled=true;formMessage.textContent='Saving...';const{error}=await db.rpc('admin_upsert_household',{p_id:familyId.value||null,p_name:familyName.value.trim(),p_token:code,p_email:familyEmail.value.trim()||null,p_phone:familyPhone.value.trim()||null,p_category:familyCategory.value,p_event_ids:eventIds});saveFamily.disabled=false;if(error){formMessage.textContent=error.message;return}familyDialog.close();await loadAll()}
async function removeFamily(){if(!state.editing||!confirm('Delete this family, event assignments and RSVP? This cannot be undone.'))return;deleteFamily.disabled=true;const{error}=await db.rpc('admin_delete_household',{p_id:state.editing});deleteFamily.disabled=false;if(error){formMessage.textContent=error.message;return}familyDialog.close();await loadAll()}
async function copyLink(code){await navigator.clipboard.writeText(`${location.origin}/invite.html?token=${code}`);managerMessage.textContent=`Invitation link copied for ${code}.`;setTimeout(()=>managerMessage.textContent='',2500)}function openWhatsApp(id){const i=state.invitations.find(x=>x.id===id);if(!i.phone){alert('Add a phone number first.');return}const msg=`Hi ${i.primary_name},

Bandhav & Shreya would be delighted to celebrate with you.

Invitation code: ${i.token}
Website: ${SITE_CONFIG.SITE_URL}

Please RSVP by October 10, 2026.`;window.open(`https://wa.me/${i.phone.replace(/\D/g,'')}?text=${encodeURIComponent(msg)}`,'_blank')}
function exportData(){const event=state.events.find(e=>e.id===state.selected),list=event?invitationsForEvent(event.id):state.invitations;const rows=[['Family','Code','Email','Phone','Category','Status','Expected people','Events'],...list.map(i=>[i.primary_name,i.token,i.email||'',i.phone||'',i.category||'',statusFor(i,state.selected),attendanceFor(i,state.selected),state.assignments.filter(a=>a.invitation_id===i.id).map(a=>state.events.find(e=>e.id===a.event_id)?.name).filter(Boolean).join('; ')])];const csv=rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`${event?.slug||'all'}-families.csv`;a.click()}
googleSignIn.onclick=login;signOut.onclick=logout;deniedSignOut.onclick=logout;addFamily.onclick=()=>openFamily();closeDialog.onclick=cancelDialog.onclick=()=>familyDialog.close();familyName.oninput=()=>{if(!state.editing)familyCode.value=makeCode(familyName.value);updatePreview()};familyCode.oninput=()=>{familyCode.value=familyCode.value.toUpperCase();updatePreview()};familyForm.onsubmit=saveFamilyRecord;deleteFamily.onclick=removeFamily;familySearch.oninput=renderFamilies;statusFilter.onchange=renderFamilies;refreshData.onclick=loadAll;exportCsv.onclick=exportData;db.auth.getSession().then(({data})=>route(data.session));db.auth.onAuthStateChange((_e,s)=>route(s));
